### ISSUE TITLE
"product_details.json file missing ?

### ISSUE THREAD

**Issue by jomit** [microsoft/Synapse-AI-Retail-Recommender#28]
It seems the "product_details.json" file mentioned here is missing ? 
https://github.com/microsoft/Synapse-AI-Retail-Recommender/tree/master/Resource_Deployment#step-22-upload-additional-dataset

**Comment by Dongbumlee** [comment]
Hi Jomit, You can find it from here - https://github.com/microsoft/Synapse-AI-Retail-Recommender/blob/master/Analytics_Deployment/data/product_detail.json
